<?php
/**
 * Created by PhpStorm.
 * User: xuliulei
 * Date: 18-4-17
 * Time: 下午3:00
 */

namespace App\Controller\Admin;


use App\Utils\Util;
use App\ViewController;
use Conf\ErrorCode;

class Base extends ViewController
{
    protected $adminUser = null;

    function index()
    {
        // TODO: Implement index() method.

    }

    function actionNotFound($actionName = null, $arguments = null)
    {
        // TODO: Implement actionNotFound() method.
    }

    function checkLoginStatus()
    {
        if ($this->adminUser !== null){

            $adminUser = json_decode($this->adminUser,true);
            $id_token = $adminUser['id_token'];
            $arr = explode('|', $id_token);
            $userId = $arr[0];
            $token = $arr[1];
            $adminUserDb = Util::buildInstance('\App\DB\AdminUserDB');
            $result = $adminUserDb->validateIdToken($userId, $token);
        }else{

            $params = $this->request()->getRequestParam();
            $idToken = $params['id_token'] ?? null;
            if ($idToken == null) {
                Util::printError($this, ErrorCode::ERROR_LOGIN, '当前未登录', 'Admin/User/login.html', $this->api);
                $this->response()->end();
                return false;
            }
            $arr = explode('|', $idToken);
            $userId = $arr[0];
            $token = $arr[1];
            $adminUserDb = Util::buildInstance('\App\DB\AdminUserDB');
            $result = $adminUserDb->validateIdToken($userId, $token);
        }

        if (!$result) {
            Util::printError($this, ErrorCode::ERROR_LOGIN, '当前未登录', 'Admin/User/login.html', $this->api);
            $this->response()->end();
            return false;
        }

    }

    function onRequest($actionName)
    {
        parent::onRequest($actionName); // TODO: Change the autogenerated stub
        $data = $this->request()->getCookieParams('adminUser');
        if (isset($data)){
            $this->adminUser = $data;
        }else{
            $this->adminUser = null;
        }
    }

    function afterAction()
    {
        // TODO: Implement afterAction() method.
    }
}